# Generated by Django 4.1 on 2023-04-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislikereview',
            name='Review',
        ),
        migrations.RemoveField(
            model_name='likedislikereview',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='ratingmovie',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='ratingmovie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='IP_addres',
        ),
        migrations.DeleteModel(
            name='LikeDislikeReview',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
        migrations.DeleteModel(
            name='RatingMovie',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
